void setBuildStatus(String message, String state) {
    step([
            $class            : "GitHubCommitStatusSetter",
            reposSource       : [$class: "ManuallyEnteredRepositorySource", url: "${GIT_URL}"],
            contextSource     : [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
            errorHandlers     : [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
            statusResultSource: [
                    $class : "ConditionalStatusResultSource",
                    results: [[$class: "AnyBuildResult", message: message, state: state]]
            ]
    ])
}

pipeline {
    agent any
    stages {
        stage('Dummy console print') {
            steps {
                echo 'Beginning...'
            }
        }
        stage('Checkstyle') {
            steps {
                bat 'mvn checkstyle:check'
            }
        }
        stage('Tests') {
            steps {
                bat 'mvn test'
            }
        }
    }
    post {
        always {
            echo 'Ending...'
        }
//        success {
//            setBuildStatus("Build succeeded", "SUCCESS")
//        }
//        failure {
//            setBuildStatus("Build failed", "FAILURE")
//        }
    }
}
